<?php
/**
 * ExternalContentData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VeriCiteLmsApiV1
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * ExternalContentData Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExternalContentData implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ExternalContentData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'file_name' => 'string',
        'upload_content_type' => 'string',
        'upload_content_length' => 'int',
        'external_content_id' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'file_name' => 'fileName',
        'upload_content_type' => 'uploadContentType',
        'upload_content_length' => 'uploadContentLength',
        'external_content_id' => 'externalContentID'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'file_name' => 'setFileName',
        'upload_content_type' => 'setUploadContentType',
        'upload_content_length' => 'setUploadContentLength',
        'external_content_id' => 'setExternalContentId'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'file_name' => 'getFileName',
        'upload_content_type' => 'getUploadContentType',
        'upload_content_length' => 'getUploadContentLength',
        'external_content_id' => 'getExternalContentId'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['file_name'] = isset($data['file_name']) ? $data['file_name'] : null;
        $this->container['upload_content_type'] = isset($data['upload_content_type']) ? $data['upload_content_type'] : null;
        $this->container['upload_content_length'] = isset($data['upload_content_length']) ? $data['upload_content_length'] : null;
        $this->container['external_content_id'] = isset($data['external_content_id']) ? $data['external_content_id'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['file_name'] === null) {
            $invalid_properties[] = "'file_name' can't be null";
        }
        if ($this->container['upload_content_type'] === null) {
            $invalid_properties[] = "'upload_content_type' can't be null";
        }
        if ($this->container['upload_content_length'] === null) {
            $invalid_properties[] = "'upload_content_length' can't be null";
        }
        if ($this->container['external_content_id'] === null) {
            $invalid_properties[] = "'external_content_id' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['file_name'] === null) {
            return false;
        }
        if ($this->container['upload_content_type'] === null) {
            return false;
        }
        if ($this->container['upload_content_length'] === null) {
            return false;
        }
        if ($this->container['external_content_id'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets file_name
     * @return string
     */
    public function getFileName()
    {
        return $this->container['file_name'];
    }

    /**
     * Sets file_name
     * @param string $file_name The name of the file
     * @return $this
     */
    public function setFileName($file_name)
    {
        $this->container['file_name'] = $file_name;

        return $this;
    }

    /**
     * Gets upload_content_type
     * @return string
     */
    public function getUploadContentType()
    {
        return $this->container['upload_content_type'];
    }

    /**
     * Sets upload_content_type
     * @param string $upload_content_type The content type of the file
     * @return $this
     */
    public function setUploadContentType($upload_content_type)
    {
        $this->container['upload_content_type'] = $upload_content_type;

        return $this;
    }

    /**
     * Gets upload_content_length
     * @return int
     */
    public function getUploadContentLength()
    {
        return $this->container['upload_content_length'];
    }

    /**
     * Sets upload_content_length
     * @param int $upload_content_length The content length of the file
     * @return $this
     */
    public function setUploadContentLength($upload_content_length)
    {
        $this->container['upload_content_length'] = $upload_content_length;

        return $this;
    }

    /**
     * Gets external_content_id
     * @return string
     */
    public function getExternalContentId()
    {
        return $this->container['external_content_id'];
    }

    /**
     * Sets external_content_id
     * @param string $external_content_id External Content ID
     * @return $this
     */
    public function setExternalContentId($external_content_id)
    {
        $this->container['external_content_id'] = $external_content_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


