<?php
/**
 * ExternalContentData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * ExternalContentData Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExternalContentData implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'file_name' => 'string',
        'upload_content_type' => 'string',
        'upload_content_length' => 'int',
        'external_content_id' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'file_name' => 'fileName',
        'upload_content_type' => 'uploadContentType',
        'upload_content_length' => 'uploadContentLength',
        'external_content_id' => 'externalContentID'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'file_name' => 'setFileName',
        'upload_content_type' => 'setUploadContentType',
        'upload_content_length' => 'setUploadContentLength',
        'external_content_id' => 'setExternalContentId'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'file_name' => 'getFileName',
        'upload_content_type' => 'getUploadContentType',
        'upload_content_length' => 'getUploadContentLength',
        'external_content_id' => 'getExternalContentId'
    );
  
    
    /**
      * $file_name The name of the file
      * @var string
      */
    protected $file_name;
    
    /**
      * $upload_content_type The content type of the file
      * @var string
      */
    protected $upload_content_type;
    
    /**
      * $upload_content_length The content length of the file
      * @var int
      */
    protected $upload_content_length;
    
    /**
      * $external_content_id External Content ID
      * @var string
      */
    protected $external_content_id;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->file_name = $data["file_name"];
            $this->upload_content_type = $data["upload_content_type"];
            $this->upload_content_length = $data["upload_content_length"];
            $this->external_content_id = $data["external_content_id"];
        }
    }
    
    /**
     * Gets file_name
     * @return string
     */
    public function getFileName()
    {
        return $this->file_name;
    }
  
    /**
     * Sets file_name
     * @param string $file_name The name of the file
     * @return $this
     */
    public function setFileName($file_name)
    {
        
        $this->file_name = $file_name;
        return $this;
    }
    
    /**
     * Gets upload_content_type
     * @return string
     */
    public function getUploadContentType()
    {
        return $this->upload_content_type;
    }
  
    /**
     * Sets upload_content_type
     * @param string $upload_content_type The content type of the file
     * @return $this
     */
    public function setUploadContentType($upload_content_type)
    {
        
        $this->upload_content_type = $upload_content_type;
        return $this;
    }
    
    /**
     * Gets upload_content_length
     * @return int
     */
    public function getUploadContentLength()
    {
        return $this->upload_content_length;
    }
  
    /**
     * Sets upload_content_length
     * @param int $upload_content_length The content length of the file
     * @return $this
     */
    public function setUploadContentLength($upload_content_length)
    {
        
        $this->upload_content_length = $upload_content_length;
        return $this;
    }
    
    /**
     * Gets external_content_id
     * @return string
     */
    public function getExternalContentId()
    {
        return $this->external_content_id;
    }
  
    /**
     * Sets external_content_id
     * @param string $external_content_id External Content ID
     * @return $this
     */
    public function setExternalContentId($external_content_id)
    {
        
        $this->external_content_id = $external_content_id;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
