<?php
/**
 * ExternalContentUploadInfo
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * ExternalContentUploadInfo Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExternalContentUploadInfo implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'external_content_id' => 'string',
        'url_post' => 'string',
        'file_path' => 'string',
        'content_length' => 'int',
        'content_type' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'external_content_id' => 'externalContentID',
        'url_post' => 'urlPost',
        'file_path' => 'filePath',
        'content_length' => 'contentLength',
        'content_type' => 'contentType'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'external_content_id' => 'setExternalContentId',
        'url_post' => 'setUrlPost',
        'file_path' => 'setFilePath',
        'content_length' => 'setContentLength',
        'content_type' => 'setContentType'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'external_content_id' => 'getExternalContentId',
        'url_post' => 'getUrlPost',
        'file_path' => 'getFilePath',
        'content_length' => 'getContentLength',
        'content_type' => 'getContentType'
    );
  
    
    /**
      * $external_content_id ID used to ID the uploaded file
      * @var string
      */
    protected $external_content_id;
    
    /**
      * $url_post URL to submit the attachment to
      * @var string
      */
    protected $url_post;
    
    /**
      * $file_path The file path
      * @var string
      */
    protected $file_path;
    
    /**
      * $content_length The length of the file
      * @var int
      */
    protected $content_length;
    
    /**
      * $content_type The files content type
      * @var string
      */
    protected $content_type;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->external_content_id = $data["external_content_id"];
            $this->url_post = $data["url_post"];
            $this->file_path = $data["file_path"];
            $this->content_length = $data["content_length"];
            $this->content_type = $data["content_type"];
        }
    }
    
    /**
     * Gets external_content_id
     * @return string
     */
    public function getExternalContentId()
    {
        return $this->external_content_id;
    }
  
    /**
     * Sets external_content_id
     * @param string $external_content_id ID used to ID the uploaded file
     * @return $this
     */
    public function setExternalContentId($external_content_id)
    {
        
        $this->external_content_id = $external_content_id;
        return $this;
    }
    
    /**
     * Gets url_post
     * @return string
     */
    public function getUrlPost()
    {
        return $this->url_post;
    }
  
    /**
     * Sets url_post
     * @param string $url_post URL to submit the attachment to
     * @return $this
     */
    public function setUrlPost($url_post)
    {
        
        $this->url_post = $url_post;
        return $this;
    }
    
    /**
     * Gets file_path
     * @return string
     */
    public function getFilePath()
    {
        return $this->file_path;
    }
  
    /**
     * Sets file_path
     * @param string $file_path The file path
     * @return $this
     */
    public function setFilePath($file_path)
    {
        
        $this->file_path = $file_path;
        return $this;
    }
    
    /**
     * Gets content_length
     * @return int
     */
    public function getContentLength()
    {
        return $this->content_length;
    }
  
    /**
     * Sets content_length
     * @param int $content_length The length of the file
     * @return $this
     */
    public function setContentLength($content_length)
    {
        
        $this->content_length = $content_length;
        return $this;
    }
    
    /**
     * Gets content_type
     * @return string
     */
    public function getContentType()
    {
        return $this->content_type;
    }
  
    /**
     * Sets content_type
     * @param string $content_type The files content type
     * @return $this
     */
    public function setContentType($content_type)
    {
        
        $this->content_type = $content_type;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
