<?php
/**
 * ReportURLLinkReponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * ReportURLLinkReponse Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReportURLLinkReponse implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'url' => 'string',
        'context_id' => 'string',
        'assignment_id' => 'string',
        'user_id' => 'string',
        'external_content_id' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'url' => 'url',
        'context_id' => 'contextID',
        'assignment_id' => 'assignmentID',
        'user_id' => 'userID',
        'external_content_id' => 'externalContentID'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'url' => 'setUrl',
        'context_id' => 'setContextId',
        'assignment_id' => 'setAssignmentId',
        'user_id' => 'setUserId',
        'external_content_id' => 'setExternalContentId'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'url' => 'getUrl',
        'context_id' => 'getContextId',
        'assignment_id' => 'getAssignmentId',
        'user_id' => 'getUserId',
        'external_content_id' => 'getExternalContentId'
    );
  
    
    /**
      * $url The url to retrieve the report
      * @var string
      */
    protected $url;
    
    /**
      * $context_id Context ID.
      * @var string
      */
    protected $context_id;
    
    /**
      * $assignment_id Assignment ID.
      * @var string
      */
    protected $assignment_id;
    
    /**
      * $user_id User ID.
      * @var string
      */
    protected $user_id;
    
    /**
      * $external_content_id external Content ID
      * @var string
      */
    protected $external_content_id;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->url = $data["url"];
            $this->context_id = $data["context_id"];
            $this->assignment_id = $data["assignment_id"];
            $this->user_id = $data["user_id"];
            $this->external_content_id = $data["external_content_id"];
        }
    }
    
    /**
     * Gets url
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }
  
    /**
     * Sets url
     * @param string $url The url to retrieve the report
     * @return $this
     */
    public function setUrl($url)
    {
        
        $this->url = $url;
        return $this;
    }
    
    /**
     * Gets context_id
     * @return string
     */
    public function getContextId()
    {
        return $this->context_id;
    }
  
    /**
     * Sets context_id
     * @param string $context_id Context ID.
     * @return $this
     */
    public function setContextId($context_id)
    {
        
        $this->context_id = $context_id;
        return $this;
    }
    
    /**
     * Gets assignment_id
     * @return string
     */
    public function getAssignmentId()
    {
        return $this->assignment_id;
    }
  
    /**
     * Sets assignment_id
     * @param string $assignment_id Assignment ID.
     * @return $this
     */
    public function setAssignmentId($assignment_id)
    {
        
        $this->assignment_id = $assignment_id;
        return $this;
    }
    
    /**
     * Gets user_id
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }
  
    /**
     * Sets user_id
     * @param string $user_id User ID.
     * @return $this
     */
    public function setUserId($user_id)
    {
        
        $this->user_id = $user_id;
        return $this;
    }
    
    /**
     * Gets external_content_id
     * @return string
     */
    public function getExternalContentId()
    {
        return $this->external_content_id;
    }
  
    /**
     * Sets external_content_id
     * @param string $external_content_id external Content ID
     * @return $this
     */
    public function setExternalContentId($external_content_id)
    {
        
        $this->external_content_id = $external_content_id;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
