<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for adminConsumerNewConsumerKeyCreatePost
     *
     * 
     *
     */
    public function test_adminConsumerNewConsumerKeyCreatePost() {

    }
    
    /**
     * Test case for adminConsumerNewConsumerKeyUpdatePut
     *
     * 
     *
     */
    public function test_adminConsumerNewConsumerKeyUpdatePut() {

    }
    
    /**
     * Test case for assignmentsContextIDAssignmentIDPost
     *
     * 
     *
     */
    public function test_assignmentsContextIDAssignmentIDPost() {

    }
    
    /**
     * Test case for reportsScoresContextIDGet
     *
     * 
     *
     */
    public function test_reportsScoresContextIDGet() {

    }
    
    /**
     * Test case for reportsSubmitRequestContextIDAssignmentIDUserIDPost
     *
     * 
     *
     */
    public function test_reportsSubmitRequestContextIDAssignmentIDUserIDPost() {

    }
    
    /**
     * Test case for reportsUrlsContextIDGet
     *
     * 
     *
     */
    public function test_reportsUrlsContextIDGet() {

    }
    
}
